### ISSUE TITLE
Youtube apiUrl() is not necessary?

### ISSUE THREAD

**Issue by Dhaulagiri** [poteto/ember-lazy-video#16]
I don't see [this function](https://github.com/poteto/ember-lazy-video/blob/develop/addon/lazy-video-providers/youtube.js#L4-L6) being used anywhere, can it be removed?

**Comment by poteto** [comment]
Yeah it's not being used, but I was going to use it to programatically retrieve the video title so I can overlay it on top of the placeholder image, so it looks exactly like a YouTube embed

**Comment by Dhaulagiri** [comment]
Ahh, cool!
