### ISSUE TITLE
Issues in Ember 1.11

### ISSUE THREAD

**Issue by EmergentBehavior** [poteto/ember-lazy-video#31]
I'm getting the following deprecation warning when using this component in Ember 1.11

```
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_warning-when-binding-style-attributes.
```

Also, in 1.11, {{bind-attr ...}} is deprecated so you may want to update that in the component template (or wait until bind-attr is completed removed).

**Comment by poteto** [comment]
Hey! Thanks, I've neglected this addon a bit. Will update and fix those warnings / deprecations soon

**Comment by EmergentBehavior** [comment]
Hey -- any updates? :)

**Comment by bl4ckm0r3** [comment]
any updates on this?

**Comment by bl4ckm0r3** [comment]
hey i decided to fork and update the repo!
https://github.com/bl4ckm0r3/ember-lazy-video
