### ISSUE TITLE
Releasing a new version of the addon.

### ISSUE THREAD

**Issue by laantorchaweb** [poteto/ember-lazy-video#35]
Hi, in the current version of the repo the #31 and #23 are solved and in addition the capacity of adding custom poster/thumbnail to the videos, are you planning on publishing a new version to NPM with these changes or is something more that you want to tackle on before releasing a new version?

If this is the case let me know if there's anything I could do to help.

Thanks!

**Comment by laantorchaweb** [comment]
@poteto I know that you may be busy, but it would be great if you could push the latest version to NPM, it fixes a lot of bug so we can use it on ember 2.0 products. I'm working on a large project using this addon and it will face production on a month or so, it would be nice to have the dependencies on NPM. Thanks!

**Comment by poteto** [comment]
Hey, sorry about that! This addon has been quite neglected, I will work on bringing it up to speed with Ember 2.x this week. If I don't please harass me on Slack!

**Comment by altrim** [comment]
Any plans when this might be released with Ember 2.x support? Thanks.

**Comment by Dhaulagiri** [comment]
@poteto would you be open to accepting new work to bring this addon back up to speed (or give me or someone else interested commit bit on this)?

**Comment by poteto** [comment]
@Dhaulagiri added you

**Comment by Dhaulagiri** [comment]
@laantorchaweb 0.2.6 has been released and published with the latest set of changes that have been sitting in the develop branch.  #38 is open to bring it up to speed for ember 2.x.
